// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu6Sn3Gbqbr0p0LjhoOWEGLkQrRaZVArY',
    appId: '1:831093502721:web:d1f0e9b545039851e92100',
    messagingSenderId: '831093502721',
    projectId: 'carlio-569a3',
    authDomain: 'carlio-569a3.firebaseapp.com',
    storageBucket: 'carlio-569a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsfskUCR5W76qAbmEDaZM7T2v5GXWv4JU',
    appId: '1:831093502721:android:c784a5c762a67416e92100',
    messagingSenderId: '831093502721',
    projectId: 'carlio-569a3',
    storageBucket: 'carlio-569a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-L1-qF4y-qTCRcxNNflEHHpFHPV36fvY',
    appId: '1:831093502721:ios:703ca49615da9357e92100',
    messagingSenderId: '831093502721',
    projectId: 'carlio-569a3',
    storageBucket: 'carlio-569a3.firebasestorage.app',
    iosBundleId: 'com.codeink.stsl.carcollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-L1-qF4y-qTCRcxNNflEHHpFHPV36fvY',
    appId: '1:831093502721:ios:703ca49615da9357e92100',
    messagingSenderId: '831093502721',
    projectId: 'carlio-569a3',
    storageBucket: 'carlio-569a3.firebasestorage.app',
    iosBundleId: 'com.codeink.stsl.carcollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu6Sn3Gbqbr0p0LjhoOWEGLkQrRaZVArY',
    appId: '1:831093502721:web:1b3c907a8addae3de92100',
    messagingSenderId: '831093502721',
    projectId: 'carlio-569a3',
    authDomain: 'carlio-569a3.firebaseapp.com',
    storageBucket: 'carlio-569a3.firebasestorage.app',
  );
}
